// Code Generated by Sidekick is for learning and experimentation purposes only.

import React from 'react';
import 'bootstrap/dist/css/bootstrap.css';
import lehenga from '../assets/manish.jpg';
import anarkali from '../assets/fabindia.jpg';
import ethnic from '../assets/nallisilks.jpg';
import sharara from '../assets/mirraw.jpg';
import ghagra from '../assets/ritu.jpg';

const brands = [
  { name: 'Manish Malhotra', imgSrc: lehenga, link:"/category/silk" },
  { name: 'Fab India', imgSrc: anarkali, link:"/category/cotton" },
  { name: 'Nalli Silks', imgSrc: ethnic, link:"/category/regional" },
  { name: 'Mirraw', imgSrc: sharara ,link:"/category/salwar"},
  { name: 'Ritu Kumar', imgSrc: ghagra,link:"/category/lehenga" }
];

const Brands = () => {
  return (
    <div className="container" style={{ 
        // width: '100vh',
    //   backgroundColor: 'wheat', 
      padding: '30px', 
      borderRadius: '10px', 
      marginTop:'50px',
      marginBottom:'50px',
      boxShadow: '0 4px 8px rgba(0, 0, 0, 0.1)' 
    }}>
      <div className="row align-items-center">
        <div className="col-2 text-left">
          <h3 style={{ color: 'black' }}>Popular Brands</h3>
        </div>
        <div className="col-10">
          <div className="row justify-content-between">
            {brands.map((brand, index) => (
              <div key={index} className="col text-center">
               <a href={brand.link} style={{textDecoration:'none'}}>
                <img
                  src={brand.imgSrc}
                  alt={brand.name}
                  className="img-fluid rounded-circle"
                  style={{ width: '130px', height: '130px' }}
                />
                <p style={{ color: 'black' }}>{brand.name}</p>
                </a>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
};

export default Brands;
