// Code Generated by Sidekick is for learning and experimentation purposes only.

import React, { useRef } from "react";
import { Card, Button } from "react-bootstrap";
import { useCart } from "./CartContext";
import { useWishlist } from "./WishlistContext";
import "./All.css";


const ProductCard = ({ product }) => {
  const { addToCart } = useCart();
  const { wishlist, addToWishlist, removeFromWishlist } = useWishlist();
  const isWishlistedRef = useRef(wishlist.some(item => item.name === product.name));  

  const handleWishlistClick = () => {

    if (isWishlistedRef.current) {
      removeFromWishlist(product);
      isWishlistedRef.current = false;
    } else {
      addToWishlist(product);
      isWishlistedRef.current = true;
    }
  };

  return (
    <Card className="hover-card">
      <Card.Img
        variant="top"
        src={`${process.env.PUBLIC_URL}/images/${product.image}`}
        alt={product.name}
        style={{ width: "100%", height: "350px", objectFit: "cover" }}
      />
      <Card.Body>
        <Card.Title>{product.name}</Card.Title>
        <Card.Text>{product.description}</Card.Text>
        <Card.Text className="text-danger">${product.price}</Card.Text>
        <Button onClick={() => addToCart(product)}>Add to Cart</Button>
        
        <i
          className={`bi bi-heart${isWishlistedRef.current ? '-fill' : ''}`}
          onClick={handleWishlistClick}
          style={{
            cursor: 'pointer',
            marginLeft: '10px',
            color: isWishlistedRef.current ? 'red' : 'black'
          }}
        ></i>
      </Card.Body>
    </Card>
  );
};

export default ProductCard;