// Code Generated by Sidekick is for learning and experimentation purposes only.

import React, { useRef } from "react";
import { Card, Row, Col, Button } from "react-bootstrap";
import { useCart } from "./CartContext";
import "./All.css";
import ProductCard from "./Card";

const Carddisplay = ({ category, subcategory }) => {
  const { addToCart } = useCart();

  if (!category) {
    return <div>No category selected</div>;
  }

  const itemsToDisplay = subcategory
    ? subcategory.sarees
    : category.subcategories.flatMap((sub) => sub.sarees);

  return (
    <div className="cart-container">
      <div className="category-section">
        <Row>
          {itemsToDisplay.map((item, index) => (
            <Col xs={12} sm={6} md={4} lg={3} key={index} className="mb-4">
              <ProductCard product={item}/>
            </Col>
          ))}
        </Row>
      </div>
    </div>
  );
};

export default Carddisplay;
