// Code Generated by Sidekick is for learning and experimentation purposes only.

import React from 'react';
import { Card, Row, Col, Button, Alert, Form } from "react-bootstrap";
import { useCart } from './CartContext';
import { useNavigate } from 'react-router-dom';
import { FaTrash } from 'react-icons/fa';
import { useAuth } from './AuthContext';
import './Cart.css'; // Import custom CSS for additional styling

const Cart = () => {
  const { cart, removeFromCart, decreaseQuantity, increaseQuantity, notification } = useCart();
  const { user, setRedirectPath } = useAuth();
  const navigate = useNavigate();

  const handleBuy = (product) => {
    if (user) {
      navigate('/buy', { state: { product } });
    } else {
      alert('Please log in to proceed with the purchase.');
      setRedirectPath('/buy');
      navigate('/login');
    }
  };

  return (
    <div className="cart-container">
      <h1>Shopping Cart</h1>
      {notification && <Alert variant="success">{notification}</Alert>}
      <Row>
        {cart.map((product, index) => (
          <Col xs={12} sm={6} md={4} lg={3} key={index} className="mb-4">
            <Card>
              <Card.Img variant="top" src={`${process.env.PUBLIC_URL}/images/${product.image}`} alt={product.name} 
              style={{ width: "100%", height: "350px", objectFit: "cover" }}/>
              <Card.Body>
                <Card.Title>{product.name}</Card.Title>
                <Card.Text>{product.description}</Card.Text>
                <Card.Text className="text-danger">Total: ₹{(product.price * product.quantity).toFixed(2)}</Card.Text>
                <Card.Text>Quantity: {product.quantity}</Card.Text>
                <Button variant="success" onClick={() => increaseQuantity(product)}>&nbsp;+&nbsp;</Button>  &nbsp; &nbsp; &nbsp;
                <Button variant="warning" onClick={() => decreaseQuantity(product)}>&nbsp;-&nbsp;</Button> &nbsp; &nbsp; &nbsp;
                <Button variant="danger" onClick={() => removeFromCart(product)}>Remove</Button>
              </Card.Body>
            </Card>
          </Col>
        )}
      </Row>
    </div>
  );
};

export default Cart;
