// Code Generated by Sidekick is for learning and experimentation purposes only.

import React, { useEffect } from "react";
import { Modal, Button } from "react-bootstrap";
import { useCart } from "./CartContext";

const CartModal = () => {
  const { showModal, handleCloseModal } = useCart();

  useEffect(() => {
    if (showModal) {
      const timer = setTimeout(() => {
        handleCloseModal();
      }, 1000); 

      return () => clearTimeout(timer); // Cleanup the timer on unmount or when showModal changes
    }
  }, [showModal, handleCloseModal]);

  return (
    <Modal show={showModal} onHide={handleCloseModal}>
      <Modal.Body style={{ textAlign: "center", justifyContent: "center" }}>
        <p>Item added</p>
      </Modal.Body>
    </Modal>
  );
};

export default CartModal;
