// Code Generated by Sidekick is for learning and experimentation purposes only.
import React, { useState, useEffect } from 'react';
import { useParams } from 'react-router-dom';
import Carddisplay from './Carddisplay';
import './All.css';

const CategoryPage = () => {
  const { categoryName, subcategoryName } = useParams();
  const [category, setCategory] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch('http://localhost:3000/categories')
      .then(response => response.json())
      .then(data => {
        const categoryData = data.find(cat => cat.name.toLowerCase() === categoryName.toLowerCase());
        setCategory(categoryData);
        setLoading(false);
      })
      .catch(error => {
        console.error('Error fetching data:', error);
        setLoading(false);
      });
  }, [categoryName]);

 

  if (!category) {
    return <div>Category not found</div>;
  }

  const subcategory = subcategoryName 
    ? category.subcategories.find(sub => sub.name.toLowerCase() === subcategoryName.toLowerCase())
    : null;

  if (subcategoryName && !subcategory) {
    return <div>Subcategory not found</div>;
  }

  return (
    <div className='container'>
      <div className='cat'>
        
        <h1>{category.name}</h1>
      </div>
      <Carddisplay category={category} subcategory={subcategory} />
    </div>
  );
};


export default CategoryPage;
