// Code Generated by Sidekick is for learning and experimentation purposes only.

import React from 'react';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faFacebook, faInstagram, faTwitter } from '@fortawesome/free-brands-svg-icons';
import './Footer.css'; // Assuming you have a CSS file for styling

const Footer = () => {
    return (
       <div className='foot'>
        <footer className="footer">
            <div className="footer-container">
                <div className="footer-section">
                    <h4>About Us</h4>
                    <p>Discover the finest collection of sarees at our store. Our mission is to bring you the best quality and designs from across India.</p>
                </div>
                <div className="footer-section">
                    <h4>Customer Service</h4>
                    <ul>
                        <li><a href="/contact">Contact Us</a></li>
                        <li><a href="/faq">FAQ</a></li>
                        <li><a href="/returns">Returns</a></li>
                        <li><a href="/shipping">Shipping Info</a></li>
                    </ul>
                </div>
                <div className="footer-section follow-us-section">
                    <h4 class="one">Follow Us</h4>
                    <ul className="social-media">
                        <li>
                            <a href="https://facebook.com" target="_blank" rel="noopener noreferrer">
                                <FontAwesomeIcon icon={faFacebook} />
                            </a>
                        </li>
                        <li>
                            <a href="https://instagram.com" target="_blank" rel="noopener noreferrer">
                                <FontAwesomeIcon icon={faInstagram} />
                            </a>
                        </li>
                        <li>
                            <a href="https://twitter.com" target="_blank" rel="noopener noreferrer">
                                <FontAwesomeIcon icon={faTwitter} />
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div className="footer-bottom">
                <p>&copy; 2025 Saree E-Commerce. All rights reserved.</p>
            </div>
        </footer>
        </div> 
    );
};

export default Footer;
