// Code Generated by Sidekick is for learning and experimentation purposes only.
import React from 'react';
import kalamkari1 from '../assets/kalamkari1.jpg';
import banarsi from '../assets/banarsi1.webp'
import madhubani from '../assets/madubani4.webp'
import chanderi from '../assets/chanderi2.webp'
import partywear from '../assets/party2.webp'
import './Grid.css';

const ImageCard = ({ imageUrl, title, className, link }) => (
 
  <div className={`image-card ${className}`}>
     <a href={link}>
    <img src={imageUrl} alt={title} className="image" />
    
    
    <div className="title">{title}</div>
    </a>
  </div>
  
);

const Grid = () => {
  const images = [
    { imageUrl: kalamkari1, title: 'Kalamkari Silks', className: 'large', link:"/category/cotton" },
    { imageUrl: banarsi, title: 'Banarasi Silks', className: 'medium', link:"/category/silk/subcategory/mysoresilk" },
    { imageUrl: chanderi, title: 'Chanderi Cotton', className: 'small', link:"/category/cotton"},
    { imageUrl: madhubani, title: 'Madhubani', className: 'small', link:"/category/cotton/subcategory/madhubani" },
    { imageUrl: partywear, title: 'Lehenga', className: 'large',link:"/category/lehenga" },
    { imageUrl: "https://media.istockphoto.com/id/105680592/photo/indian-scarves-in-many-colors-for-display.jpg?s=612x612&w=0&k=20&c=eGIl-xZv6K7miZSCQjvezFqSoas3H6uVZ4OR7cAhDxs=", title: 'Regional Sarees Materials', className: 'medium1' },
  ];

  return (
    
    <div className="gallery">
      {images.map((image, index, link) => (
        <ImageCard key={index} imageUrl={image.imageUrl} title={image.title} className={image.className} link={image.link} />
      ))}
    </div>
   
  );
};

export default Grid;
