// Code Generated by Sidekick is for learning and experimentation purposes only.
import React from 'react';
import kalamkari1 from '../assets/kalamkari1.jpg';
import banarsi from '../assets/banarsi1.webp'
import madhubani from '../assets/madubani4.webp'
import chanderi from '../assets/chanderi2.webp'
import partywear from '../assets/party2.webp'
import './Grid.css';

const ImageCard = ({ imageUrl, title, className }) => (
  <div className={`image-card ${className}`}>
    <img src={imageUrl} alt={title} className="image" />
    <div className="title">{title}</div>
  </div>
);

const Grid = () => {
  const images = [
    { imageUrl: kalamkari1, title: 'Kalamkari Silks', className: 'large' },
    { imageUrl: banarsi, title: 'Banarasi Silks', className: 'medium' },
    { imageUrl: chanderi, title: 'Chanderi Cotton', className: 'small' },
    { imageUrl: madhubani, title: 'Madhubani', className: 'small' },
    { imageUrl: partywear, title: 'Lehenga', className: 'large' },
    { imageUrl: "https://media.istockphoto.com/id/105680592/photo/indian-scarves-in-many-colors-for-display.jpg?s=612x612&w=0&k=20&c=eGIl-xZv6K7miZSCQjvezFqSoas3H6uVZ4OR7cAhDxs=", title: 'Regional Sarees Materials', className: 'medium1' },
  ];

  return (
    <div className="gallery">
      {images.map((image, index) => (
        <ImageCard key={index} imageUrl={image.imageUrl} title={image.title} className={image.className} />
      ))}
    </div>
  );
};

export default Grid;
