// Code Generated by Sidekick is for learning and experimentation purposes only.

import React from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from './AuthContext';  // Import useAuth
import './Auth.css';

const Logout = () => {
  const navigate = useNavigate();
  const { logout } = useAuth();  // Get logout function from AuthContext

  const handleLogout = () => {
    logout();
    navigate('/login');
  };

  return (
    <button className="logout-button" onClick={handleLogout}>
      Logout
    </button>
  );
};

export default Logout;
