// Code Generated by Sidekick is for learning and experimentation purposes only.

import React from 'react';
import { useWishlist } from './WishlistContext';
import { Card, Row, Col, Button } from 'react-bootstrap';
import { useCart } from './CartContext';

const WishlistPage = () => {
  const { wishlist, removeFromWishlist } = useWishlist();
  const { addToCart } = useCart();

  return (
    <div>
      <h1>My Wishlist</h1>
      <Row>
        {wishlist.length === 0 ? (
          <p>Your wishlist is empty.</p>
        ) : (
          wishlist.map(product => (
            <Col xs={12} sm={6} md={4} lg={3} key={product.id} className="mb-4">
              <Card className="hover-card">
                <Card.Img
                  variant="top"
                  src={`${process.env.PUBLIC_URL}/images/${product.image}`}
                  alt={product.name}
                  style={{ width: "100%", height: "350px", objectFit: "cover" }}
                />
                <Card.Body>
                  <Card.Title>{product.name}</Card.Title>
                  <Card.Text>{product.description}</Card.Text>
                  <Card.Text className="text-danger">${product.price}</Card.Text>
                  <Button onClick={() => addToCart(product)}>Add to Cart</Button>
                  <Button variant="danger" onClick={() => removeFromWishlist(product)}>Remove</Button>
                </Card.Body>
              </Card>
            </Col>
          ))
        )}
      </Row>
    </div>
  );
};

export default WishlistPage;
