// Code Generated by Sidekick is for learning and experimentation purposes only.

import React, { createContext, useContext, useState, useEffect } from 'react';

const WishlistContext = createContext();

export const useWishlist = () => useContext(WishlistContext);

export const WishlistProvider = ({ children }) => {
  const [wishlist, setWishlist] = useState(() => {
    const savedWishlist = localStorage.getItem('wishlist');
    return savedWishlist ? JSON.parse(savedWishlist) : [];
  });

  useEffect(() => {
    localStorage.setItem('wishlist', JSON.stringify(wishlist));
  }, [wishlist]);

  const addToWishlist = (product) => {
    setWishlist((prevWishlist) => {
      const existingProduct = prevWishlist.find(item => item.name === product.name);
      if (existingProduct) {
        // If the product is already in the wishlist, do nothing
        return prevWishlist;
      } else {
        // If the product is not in the wishlist, add it
        return [...prevWishlist, product];
      }
    });
  };

  const removeFromWishlist = (product) => {
    setWishlist(prevWishlist => prevWishlist.filter(item => item.name !== product.name));
  };

  return (
    <WishlistContext.Provider value={{ wishlist, addToWishlist, removeFromWishlist }}>
      {children}
    </WishlistContext.Provider>
  );
};
